server:
  port: 9001
spring:
  application:
    name: choice-consumer
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka,http://127.0.0.1:7002/eureka.http://127.0.0.1:7003/eureka
  instance:
      instance-id: choice-consumer01
      prefer-ip-address: true
      ip-address: 127.0.0.1
feign:
   hystrix:
      enabled: true

